version: "3"
services:
  ui:
    image: fakadata:ui
    ports:
      - "3000:80"
  api:
    image: fakadata:api
    ports:
      - "8080:80"
    volumes:
      - "db-data:/data"
  node-red:
    image: stream-analytics-model
    ports:
      - "1880:1880"
volumes:
  db-data:
